if: branch = master
language: minimal
git:
  depth: 1
  submodules_depth: 1
before_install:
  # This workaround is required to avoid libstdc++ errors while running "extended" hugo with SASS support.
  - wget -q -O libstdc++6 http://security.ubuntu.com/ubuntu/pool/main/g/gcc-5/libstdc++6_5.4.0-6ubuntu1~16.04.10_amd64.deb
  - sudo dpkg --force-all -i libstdc++6
install:
  - wget -q -O hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.46/hugo_extended_0.46_Linux_64bit.deb
  - sudo dpkg -i hugo.deb
script:
  - hugo # From version 0.43 hugo automatically creates css files from sass/scss
deploy:
  - provider: pages
    repo: DariaGreen/daria.green
    fqdn: daria.green
    target-branch: gh-pages
    local-dir: public
    skip-cleanup: true
    github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure.
    keep-history: true
    on:
      branch: master
