if: branch = master
dist: xenial
language: minimal
env:
  global:
    - HUGO_RELEASE=0.58.3
git:
  depth: 1
  submodules_depth: 1
install:
  - wget -q -O hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_RELEASE}/hugo_extended_${HUGO_RELEASE}_Linux-64bit.deb
  - sudo dpkg -i hugo.deb
script:
  - hugo # From version 0.43 hugo automatically creates css files from sass/scss
deploy:
  - provider: pages
    repo: DariaGreen/daria.green
    fqdn: daria.green
    target-branch: gh-pages
    local-dir: public
    skip-cleanup: true
    github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure.
    keep-history: true
    on:
      branch: master
