if: branch = master
language: minimal
git:
  depth: 1
  submodules_depth: 1
install:
  - gem install sass
  - wget -O /tmp/hugo.tar.gz https://github.com/gohugoio/hugo/releases/download/v0.34/hugo_0.34_Linux-64bit.tar.gz
  - mkdir /tmp/hugo
  - tar -xzf /tmp/hugo.tar.gz -C /tmp/hugo
  - export PATH=/tmp/hugo:$PATH
script:
  - bash build.sh
deploy:
  - provider: pages
    repo: DariaGreen/daria.green
    fqdn: daria.green
    target-branch: gh-pages
    local-dir: public
    skip-cleanup: true
    github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure.
    keep-history: true
    on:
      branch: master
