# Site settings
title: Блог Даши
email: ask@daria.green
description: > # this means to ignore newlines until "baseurl:"
  Всестороннее развитие
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://daria.green" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# This is the list of pages to incldue in the header of the website.
#pages_list:       {'О блоге':'/about','Архив':'/archive','RSS подписка':'/atom.xml'}
